export const facilities = [
  "Free WiFi",
  "Non-smoking rooms",
  "Restaurant",
  "Airport shuttle",
  "Room service",
  "Family rooms",
  "Bar",
  "Spa and wellness centre",
  "24-hour front desk",
  "Hot tub/Jacuzzi",
  "Sauna",
  "Air conditioning",
  "Fitness centre",
  "Water park",
  "Garden",
  "Swimming pool",
  "Terrace",
];
